/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Aplicacion.Extractor;
import Aplicacion.Graduado;
import java.awt.Font;
import java.util.HashMap;
import java.util.concurrent.ConcurrentLinkedQueue;

/**
 *
 * @author crist    
 */
public class filtrarInformacion extends javax.swing.JDialog {

    /**
     * Creates new form filtrarInformacion
     */
    private MostrarInformacion app;

    public filtrarInformacion(MostrarInformacion parent, boolean modal) {
        super(parent, modal);
        app = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreGraduado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paisGraduado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cargoActualGraduado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filtrar = new javax.swing.JButton();
        sinFltrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lugarEstudioGraduado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nombreEstudioGraduado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechaEstudioGraduado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre del graduado");

        nombreGraduado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreGraduadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Pais del Graduado");

        jLabel3.setText("Cargo Actual del Graduado");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel4.setText("FILTRAR INFORMACIÓN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Rellene los campos que desee que la aplicación realice el filtro de información");

        filtrar.setText("Filtrar ");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        sinFltrar.setText("Sin filtros");
        sinFltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinFltrarActionPerformed(evt);
            }
        });

        jLabel6.setText("Lugar Estudio del graduado");

        jLabel7.setText("Nombre Estudio del graduado");

        jLabel8.setText("Fecha Estudio del graduado ");

        fechaEstudioGraduado.setToolTipText("ej: 2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paisGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cargoActualGraduado))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(filtrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinFltrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lugarEstudioGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreEstudioGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaEstudioGraduado, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(paisGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cargoActualGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lugarEstudioGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(nombreEstudioGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fechaEstudioGraduado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrar)
                    .addComponent(sinFltrar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreGraduadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreGraduadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreGraduadoActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        HashMap<String, String> filtros = new HashMap<>();
        if (!nombreGraduado.getText().equals("")) {
            filtros.put("nombreGraduado", nombreGraduado.getText());
        } else if (!paisGraduado.getText().equals("")) {
            filtros.put("paisGraduado", paisGraduado.getText());
        } else if (!cargoActualGraduado.getText().equals("")) {
            filtros.put("cargoActualGraduado", cargoActualGraduado.getText());
        } else if (!lugarEstudioGraduado.getText().equals("")) {
            filtros.put("lugarEstudioGraduado", lugarEstudioGraduado.getText());
        } else if (!nombreEstudioGraduado.getText().equals("")) {
            filtros.put("nombreEstudioGraduado", nombreEstudioGraduado.getText());
        }else if (!fechaEstudioGraduado.getText().equals("")) {
            filtros.put("fechaEstudioGraduado", fechaEstudioGraduado.getText());
        }
        app.getApp().pintarDatosFiltradosGraduado(new Extractor().filtrar(filtros, app.getApp().getGraduados()));
        app.getApp().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_filtrarActionPerformed

    private void sinFltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinFltrarActionPerformed
        app.getApp().pintarDatosFiltradosGraduado(app.getApp().graduados.toArray(new Graduado[app.getApp().graduados.size()]));
        app.getApp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sinFltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cargoActualGraduado;
    private javax.swing.JTextField fechaEstudioGraduado;
    private javax.swing.JButton filtrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lugarEstudioGraduado;
    private javax.swing.JTextField nombreEstudioGraduado;
    private javax.swing.JTextField nombreGraduado;
    private javax.swing.JTextField paisGraduado;
    private javax.swing.JButton sinFltrar;
    // End of variables declaration//GEN-END:variables
}
